author: ParisNeo
category: context_updater
class_name: LongTermMemoryFunction
creation_date_time: '2025-02-09T23:05:21.407756'
description: Builds a long term memory out of your discussions, if it is active, it
  records relevant information
examples:
- What time is it right now?
- Can you tell me the current time?
last_update_date_time: '2025-02-09T23:05:21.407756'
name: long_term_memory
parameters: {}
returns:
  current_time:
    description: ISO format timestamp of current server time
    format: date-time
    type: string
version: 1.0.0
