author: ParisNeo
category: text_processing
class_name: WordCountFunction
creation_date_time: '2023-10-15T12:00:00.000000'
description: Counts the number of words in a given text.
examples:
- Count the words in this sentence.
- How many words are in "Hello, world!"?
last_update_date_time: '2023-10-15T12:00:00.000000'
name: word_count
static_parameters: []
parameters:
- description: The text to count the words in.
  name: text
  type: str
returns:
  status:
    description: The number of words in the text.
    type: str
version: 1.0.0
